// src/app/review/review-problem/review-problem.component.ts
import { Input, Component, OnInit, Output, EventEmitter } from '@angular/core';

@Component({
  selector: 'app-review-problem',
  templateUrl: './review-problem.component.html',
  styleUrls: ['./review-problem.component.scss']
})
export class ReviewProblemComponent implements OnInit {
  selected: boolean = false;
  @Input() problem;
  @Output() problemChanged: EventEmitter<string> = new EventEmitter<string>();
  constructor() {}
  problemClick() {
    this.selected = !this.selected;
    this.problemChanged.emit('problemChanged');
  }
  ngOnInit() {}
}

<li (touchstart)="problemClick()" [ngClass]="{'active': selected}">
  <span class="iconfont icon-gouxuan"></span>
  <a href="javascript:">{{problem}}</a>
</li>

// src/components/ReviewProblem.vue
<template>
  <li @touchstart="problemClick" :class="{active: selected}">
    <span class="iconfont icon-gouxuan" />
    <a href="javascript:">{{problem}}</a>
  </li>
</template>

<script>
  export default {
    props: ['problem'],
    data() {
      return {
        selected: false
      };
    },
    methods: {
      problemClick() {
        this.selected = !this.selected;
        this.$emit('problemChanged');
      }
    }
  };
</script>

<style lang="scss" scoped>
  @import "../scss/Review.scss";
</style>
