// src/app/review/review-modal/review-modal.component.ts
import { Component, OnInit, EventEmitter, Input, Output } from '@angular/core';

@Component({
  selector: 'app-review-modal',
  templateUrl: './review-modal.component.html',
  styleUrls: ['./review-modal.component.scss']
})
export class ReviewModalComponent implements OnInit {
  constructor() {}
  @Input() isModalOpen: boolean;
  @Output() modalClosed: EventEmitter<string> = new EventEmitter<string>();
  @Output() submitForm: EventEmitter<string> = new EventEmitter<string>();
  onCloseModal() {
    this.modalClosed.emit('modalClosed');
  }
  onConfirmSubmit() {
    this.submitForm.emit('submitForm');
  }
  ngOnInit() {}
}

<section [ngClass]="{'modal':true, 'hide': !isModalOpen }">
  <div class="modalCenter">
    <span class="iconfont icon-guanbidanchuang close" (touchstart)="onCloseModal()"></span>
    <h4>提交后无法修改</h4>
    <p>确定提交吗？</p>
    <div class="buttons">
      <a class="close" (touchstart)="onCloseModal()">
        再想想
      </a>
      <a class="confirm" (touchstart)="onConfirmSubmit()">
        确定
      </a>
    </div>
  </div>
</section>

// src/components/ReviewModal.vue
<template>
  <section :class="[`modal`, { hide: !isModalOpen }]">
    <div class="modalCenter">
      <span class="iconfont icon-guanbidanchuang close" @touchstart="onCloseModal" />
      <h4>提交后无法修改</h4>
      <p>确定提交吗？</p>
      <div class="buttons">
        <a class="close" @touchstart="onCloseModal">
          再想想
        </a>
        <a class="confirm" @touchstart="onConfirmSubmit">
          确定
        </a>
      </div>
    </div>
  </section>
</template>

<script>
  export default {
    props: {
      isModalOpen: {
        required: true,
        type: Boolean
      }
    },
    data() {
      return {};
    },
    methods: {
      onCloseModal() {
        this.$emit('modalClosed');
      },
      onConfirmSubmit() {
        this.$emit('submitForm');
      }
    }
  };
</script>

<style lang="scss">
  @import "../scss/Review.scss";
</style>
