// src/components/ReviewProblemCategory.vue
<template>
  <article class="reviewItem">
    <div :class="['reviewItemHeader', {active: review.id === selectedReviewId, valueMoreThanOne: selectedProblems.length > 0}]"
      @touchstart="emitProblemCategory(review.id)">
      <span class="iconfont icon-gouxuan" /> {{review.problemCategory}}
    </div>
    <ul :class="{ hide: review.id !== selectedReviewId }">
      <template v-for="(problem,index) in review.problems">
        <app-problem :key="index" :problem="problem" @problemChanged="onProblemChange(review.id, problem)"></app-problem>
      </template>
    </ul>
  </article>
</template>

<script>
  import ReviewProblem from './ReviewProblem';

  export default {
    components: {
      'app-problem': ReviewProblem
    },
    data() {
      return {
        selectedProblems: []
      };
    },
    props: {
      review: {
        required: true,
        type: Object
      },
      selectedReviewId: {
        required: true,
        type: Number
      }
    },
    methods: {
      emitProblemCategory(id) {
        this.$emit('problemCategoryChanged', id);
      },
      onProblemChange(id, problem) {
        if (this.selectedProblems.indexOf(problem) > -1) {
          this.selectedProblems.splice(this.selectedProblems.indexOf(problem), 1);
        } else {
          this.selectedProblems.push(problem);
        }
        this.$emit('problemsChanged', {reviewId: id, problems: this.selectedProblems});
      }
    }
  };
</script>

<style lang="scss" scoped>
  @import "../scss/Review.scss";
</style>

// src/app/review/review-problem-category/review-problem-category.component.ts
import { IReview } from './../review';
import { Component, OnInit, Input, Output, EventEmitter } from '@angular/core';

@Component({
  selector: 'app-review-problem-category',
  templateUrl: './review-problem-category.component.html',
  styleUrls: ['./review-problem-category.component.scss']
})
export class ReviewProblemCategoryComponent implements OnInit {
  selectedProblems: any[] = [];
  @Input() review: IReview;
  @Input() selectedReviewId: number;
  @Output() problemCategoryChanged: EventEmitter<number> = new EventEmitter<number>();
  @Output() problemsChanged: EventEmitter<Object> = new EventEmitter<Object>();
  constructor() {}

  emitProblemCategory(id) {
    this.problemCategoryChanged.emit(id);
  }
  onProblemChange(id, problem) {
    if (this.selectedProblems.indexOf(problem) > -1) {
      this.selectedProblems.splice(this.selectedProblems.indexOf(problem), 1);
    } else {
      this.selectedProblems.push(problem);
    }
    this.problemsChanged.emit({ reviewId: id, problems: this.selectedProblems });
  }
  ngOnInit() {}
}

<article class="reviewItem">
  <div [ngClass]="{'reviewItemHeader':true, 'active': review.id === selectedReviewId, 'valueMoreThanOne': selectedProblems.length > 0}"
    (touchstart)="emitProblemCategory(review.id)">
    <span class="iconfont icon-gouxuan"></span> {{review.problemCategory}}
  </div>
  <ul [ngClass]="{ hide: review.id !== selectedReviewId }">
    <ng-container *ngFor="let problem of review.problems; let index = index;">
      <app-review-problem [problem]=problem (problemChanged)="onProblemChange(review.id, problem)"></app-review-problem>
    </ng-container>
  </ul>
</article>
